flags: {}
packages:
- '.'
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- DebugTraceHelpers-0.12
- happstack-authenticate-2.1.4
- time-recurrence-0.9.2
- NoTrace-0.3.0.1
resolver: lts-5.11
ghc-options: 
    "*": -DNO_INTERPRET_QUOTES
